# Generated by Django 5.0 on 2024-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='period',
        ),
        migrations.AddField(
            model_name='game',
            name='hint',
            field=models.CharField(default='prepare to die', max_length=200),
            preserve_default=False,
        ),
    ]
